/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muzima_util_FileUtils */

#ifndef _Included_com_muzima_util_FileUtils
#define _Included_com_muzima_util_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muzima_util_FileUtils
 * Method:    getFileDescriptorOwner
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_muzima_util_FileUtils_getFileDescriptorOwner
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
